name: 'TestOps sync script repository'
description: 'Auto-sync changes from script repo to TestOps'
inputs:
  path:  
    description: 'Path to Katalon Studio repository'
    required: false
    default: './'
  username:
    description: 'Username to auth Basic Auth'
    required: true
  password:
    description: 'Password to auth Basic Auth'
    required: true
  token:
    description: 'Token to get s3 presigned URL'
    required: true
  github-url:
    description: 'Github url to get presigned URL'
    require: true
  testops-base-url:
    description: 'TestOps base URL'
outputs:
  repository: # id of output
    description: 'The JSON contains the repository Test Suite Collections, Test Suites, Test Cases and Profiles'
runs:
  using: 'node16'
  main: 'dist/index.js'