name: 'TestOps sync script repository'
description: 'Auto-sync changes from script repo to TestOps'
outputs:
  repository: # id of output
    description: 'The JSON contains the repository Test Suite Collections, Test Suites, Test Cases and Profiles'
runs:
  using: 'node16'
  main: 'index.js'