name: Generate repository's metadata
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
        default: master
    secrets:
      username:
        required: true
      password:
        required: true
      token:
        required: true

jobs:
  generate-a-repository-json:
    runs-on: ubuntu-latest
    name: Generate repository json
    steps:
      - uses: actions/checkout@v3
        with: 
          path: target-repo

      # - name: Checkout web-service-tests
      #   uses: actions/checkout@v3
      #   with: 
      #     repository: katalon-studio-samples/testops-sync-script-repo-action
      #     ref: {{ inputs.branch }}
      #     path: target-repo

      - name: Scan repository
        uses: katalon-studio-samples/testops-sync-script-repo-action@TES-1829
        with: 
          path: target-repo
          testops-base-url: ${{ inputs.testops-base-url }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          token: ${{ secrets.token }}
