name: Generate repository.json
on:
  workflow_call:
    inputs:
      repository-name:
        required: true
        type: string
      testops-base-url:
        required: true
        type: string
      username:
        required: true
        type: string
      password:
        required: true
        type: string
      token:
        required: true
        type: string
jobs:
  generate-a-repository-json:
    runs-on: ubuntu-latest
    name: Generate repository json
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Checkout web-service-tests
        uses: actions/checkout@v3
        with: 
          repository: katalon-studio-samples/${{ inputs.repository-name }}
          ref: master
          path: target-repo

      - name: Scan repository
        id: scan
        uses: ./
        with: 
          path: target-repo
          testops-base-url: ${{ inputs.testops-base-url }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
          token: ${{ inputs.token }}