on:
  push:
    branches:
      - master
      - TES-1829

env:
  TESTOPS_BASE_URL: https://testops.staging.katalon.com
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    steps:
      - name: Test
        run: |
          echo "TESTOPS_BASE_URL: $TESTOPS_BASE_URL"
          echo "USERNAME: $USERNAME"
          echo "PASSWORD: $PASSWORD"
          echo "TOKEN: $TOKEN"
  # generate-web-services-repo:
  #   uses: ./.github/workflows/generate-repo-json.yml
  #   with:
  #     repository-name: web-service-tests
  #     testops-base-url: ${{github.env.TESTOPS_BASE_URL}}
  #     username: ${{github.env.USERNAME}}
  #     password: ${{github.env.PASSWORD}}
  #     token: ${{github.env.TOKEN}}
  
  # generate-health-care-repo:
  #   uses: ./.github/workflows/generate-repo-json.yml
  #   with:
  #     repository-name: healthcare-tests
  #     testops-base-url: https://testops.staging.katalon.com
  #     username: ${{ secrets.USERNAME }}
  #     password: ${{ secrets.PASSWORD }}
  #     token: ${{ secrets.TOKEN }}
