name: Staging
on:
  push:
    branch:
      - test

jobs:
  sync-sample-staging:
    uses: ./.github/workflows/generate-upload-metadatas.yml
    with:
      testops-base-url: https://testops.staging.katalon.com
    secrets:
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
      token: ${{ secrets.TOKEN }}
